[package]
name = "runwrap"
version = "0.1.0"
authors = ["Viktor Eikman <viktor.eikman@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fancy_regex = "1.6"
lazy_static = "1.4"
textwrap = "0.13"

[dev-dependencies]
pretty_assertions = "0"
